Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-08, with the labels that each got.

#583 feature: implemented priority service
  prisma/migrations/20230731222831_make_entrant_fields_nullable/migration.sql
  prisma/schema.prisma
  src/v2/api/controllers/DocumentController.ts
  src/v2/api/dtos/PriorityDTO.ts
  src/v2/api/services/DocumentService.ts
  src/v2/database/repositories/EntrantRepository.ts
  src/v2/modules/DocumentModule.ts
  src/v2/modules/PrismaModule.ts
  src/v2/utils/exceptions/InvalidEducationProgramsException.ts
Labels: feature

#582 feature: created endpoint to save contract
  src/v2/api/ApiModule.ts
  src/v2/api/controllers/EntrantController.ts
  src/v2/api/dtos/CreateContractDTO.ts
  src/v2/api/responses/EntrantWithContractResponse.ts
  src/v2/api/services/EntrantService.ts
  src/v2/database/entities/DbEntrant.ts
  src/v2/database/repositories/EntrantRepository.ts
  src/v2/mappers/EntrantMapper.ts
  src/v2/modules/EntrantModule.ts
  src/v2/modules/MapperModule.ts
  src/v2/modules/PrismaModule.ts
  src/v2/utils/exceptions/AlreadyExistException.ts
Labels: feature

#576 refactoring #482: Changed filtering of primitive arrays with Set object
  src/v2/api/services/DisciplineTeacherService.ts
  src/v2/api/services/EmailService.ts
  src/v2/api/services/PollService.ts
  src/v2/api/services/RoleService.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/api/services/TeacherService.ts
  src/v2/api/services/UserService.ts
  src/v2/mappers/DisciplineTeacherMapper.ts
  src/v2/mappers/QuestionMapper.ts
  src/v2/mappers/StudentMapper.ts
  src/v2/mappers/TeacherMapper.ts
Labels: refactoring

#591 feature: made queue ids int
  prisma/migrations/20230801212649_make_queue_ids_int/migration.sql
  prisma/schema.prisma
  src/v2/api/controllers/AdmissionController.ts
  src/v2/api/services/AdmissionService.ts
Labels: migration

#594 enhancement: adapted document service
  Dockerfile
  src/v2/api/services/DocumentService.ts
Labels: enhancement

#597 enhancement: made IdCode replaceable
  src/v2/api/services/DocumentService.ts
Labels: enhancement

#598 enhancement: added regex for admission
  src/v2/api/controllers/DocumentController.ts
  src/v2/api/controllers/EntrantController.ts
  src/v2/api/dtos/NamesDTO.ts
  src/v2/api/dtos/PriorityDTO.ts
  src/v2/api/dtos/StudyContractDTO.ts
  src/v2/utils/GLOBALS.ts
Labels: enhancement

#600 migration: added representative data table
  prisma/migrations/20230804142412_add_representative_data/migration.sql
  prisma/schema.prisma
Labels: migration

#601 enhancement: added ability to store representative
  prisma/migrations/20230804144903_add_full_name_fields_for_representative/migration.sql
  prisma/schema.prisma
  src/v2/api/services/DocumentService.ts
Labels: enhancement

#602 migration: added details about entrant
  prisma/migrations/20230804204341_add_datails_about_entrant/migration.sql
  prisma/schema.prisma
Labels: migration

#603 feature: added endpoint for creating contract
  src/v2/api/controllers/DocumentController.ts
  src/v2/api/controllers/EntrantController.ts
  src/v2/api/dtos/FullNameDTO.ts
  src/v2/api/services/DocumentService.ts
  src/v2/api/services/EntrantService.ts
  src/v2/database/entities/DbEntrant.ts
  src/v2/database/repositories/EntrantRepository.ts
Labels: feature

#604 feature: added endpoint for deleting entrant data
  src/v2/api/controllers/EntrantController.ts
  src/v2/api/dtos/DeleteEntrantQueryDTO.ts
  src/v2/api/services/DocumentService.ts
  src/v2/api/services/EntrantService.ts
  src/v2/database/repositories/EntrantRepository.ts
Labels: feature

#610 enhancement: improved endpoint for getting contract
  src/v2/api/controllers/DocumentController.ts
  src/v2/api/pipes/EntrantByIdPipe.ts
  src/v2/api/services/DocumentService.ts
Labels: enhancement

#564 feature #532: Add endpoint for group member on schedule
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/responses/DisciplineTypeResponse.ts
  src/v2/api/responses/EventsResponse.ts
  src/v2/api/responses/GeneralEventResponse.ts
  src/v2/api/responses/MainEventInfoResponse.ts
  src/v2/api/services/DisciplineService.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/api/services/UserService.ts
  src/v2/database/repositories/EventRepository.ts
  src/v2/mappers/ScheduleMapper.ts
  src/v2/modules/ScheduleModule.ts
Labels: feature

#593 feature #573: created endpoint for general events for day period
  src/v2/api/controllers/AuthController.ts
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/mappers/ScheduleMapper.ts
  src/v2/modules/ScheduleModule.ts
  src/v2/utils/date/DateService.ts
  src/v2/utils/exceptions/InvalidDayException.ts
Labels: feature

#615 feature #544: added endpoint for deleting event
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/pipes/EventByIdPipe.ts
  src/v2/api/services/ScheduleService.spec.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/utils/ArrayUtil.ts
Labels: feature

#621 feature #620: created endpoint to get current semester
  src/v2/api/controllers/DateController.ts
  src/v2/api/responses/SemesterResponse.ts
  src/v2/api/services/ScheduleService.spec.ts
  src/v2/api/services/ScheduleService.ts
Labels: feature

#619 enhancement #617: added filtration for event endpoints
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/EventFiltrationDTO.ts
  src/v2/api/dtos/GeneralEventFiltrationDTO.ts
  src/v2/api/responses/EventsResponse.ts
  src/v2/api/services/ScheduleService.ts
Labels: enhancement

#570 feature #543: created endpoint to update event
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/UpdateEventDTO.ts
  src/v2/api/pipes/EventByIdPipe.ts
  src/v2/api/pipes/EventPipe.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/database/entities/DbDiscipline.ts
  src/v2/database/repositories/DisciplineRepository.ts
  src/v2/database/repositories/EventRepository.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: feature

#632 feature #575: created endpoint to get fortnight events
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/responses/EventsResponse.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/utils/exceptions/DataNotFoundException.ts
Labels: feature

#616 bugfix #527: meta comments doesn't work
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/datas/PaginatedData.ts
  src/v2/api/datas/QuestionCommentData.ts
  src/v2/api/dtos/CommentsQueryDTO.ts
  src/v2/api/pipes/CommentsQueryPipe.ts
  src/v2/api/responses/PaginatedQuestionCommentsResponse.ts
  src/v2/api/responses/PaginationDataResponse.ts
  src/v2/api/services/PollService.ispec.ts
  src/v2/api/services/PollService.ts
  src/v2/database/DatabaseUtils.ts
  src/v2/database/entities/DbQuestionWithDiscipline.ts
  src/v2/database/repositories/QuestionAnswerRepository.ts
  src/v2/mappers/QuestionMapper.spec.ts
  src/v2/mappers/QuestionMapper.ts
  src/v2/modules/TeacherModule.ts
Labels: bug

#637 feature #481: added logging through telegram
  src/v2/api/dtos/TelegramDTO.ts
  src/v2/security/exception-handler/CommonExceptions.ts
Labels: feature

#642 enhancement #639: create a global enum for permissions:
  src/v2/api/controllers/CathedraController.ts
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/controllers/DisciplineTeacherController.ts
  src/v2/api/controllers/EntrantController.ts
  src/v2/api/controllers/GroupController.ts
  src/v2/api/controllers/PollController.ts
  src/v2/api/controllers/ResourceController.ts
  src/v2/api/controllers/RoleController.ts
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/controllers/SubjectController.ts
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/security/PERMISSION.ts
Labels: enhancement

#633 documentation #631: added swagger documentation for 7 roles endpoints
  src/v2/api/controllers/RoleController.ts
  src/v2/api/dtos/CreateGrantsDTO.ts
  src/v2/api/dtos/CreateRoleDTO.ts
  src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
  src/v2/api/dtos/UpdateRoleDTO.ts
  src/v2/api/responses/GrantResponse.ts
  src/v2/api/responses/RoleResponse.ts
Labels: documentation

#653 feature #651: added endpoint for captain changing by admin
  src/v2/api/controllers/UserController.ts
  src/v2/api/services/DocumentService.ts
  src/v2/security/PERMISSION.ts
Labels: feature

#638 Documentation/add swagger documentation for groups endpoints
  src/v2/api/controllers/GroupController.ts
  src/v2/api/dtos/ApproveDTO.ts
  src/v2/api/dtos/RoleDTO.ts
  src/v2/api/responses/StudentResponse.ts
Labels: documentation

#655 bugfix #654: fixed events permissions
  src/v2/api/controllers/ScheduleController.ts
Labels: bug

#659 bugfix #658: fixed bug in update event endpoint
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/UpdateEventDTO.ts
  src/v2/api/services/ScheduleService.ts
Labels: bug

#665 enhancement #664: added field disciplineId in get event endpoint response
  src/v2/api/responses/EventResponse.ts
  src/v2/mappers/ScheduleMapper.ts
Labels: enhancement
