Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-05, with the labels that each got.

#323 refactoring #281: refactored discipline repository
  src/v2/api/discipline/DbDiscipline.ts
  src/v2/api/discipline/DisciplineMapper.ts
  src/v2/api/discipline/DisciplineModule.ts
  src/v2/api/discipline/DisciplineRepository.ts
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/group/GroupRepository.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/poll/PollService.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/teacher/DisciplineTeacherRepository.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherMapper.ts
  src/v2/api/user/StudentRepository.ts
  src/v2/security/group-guard/GroupByDisciplineGuard.ts
Labels: refactoring

#326 enhancement/upgrade-getting-teachers-method
  src/v2/api/discipline/DisciplineMapper.ts
  src/v2/api/poll/PollService.ts
  src/v2/utils/date/DateService.ts
Labels: enhancement

#328 fix #327: fixed teacher filter logic and added DateService in providers
  src/v2/api/poll/PollModule.ts
  src/v2/api/poll/PollService.ts
Labels: bug

#330 migration #325: updated schedule tables and discipline table
  prisma/migrations/20230507152900_update_schedule_tables_and_discipline_table/migration.sql
  prisma/schema.prisma
  src/v2/api/discipline/DbDiscipline.ts
  src/v2/api/discipline/DisciplineTypeRepository.ts
  src/v2/api/schedule/ScheduleController.ts
  src/v2/api/schedule/ScheduleRepository.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/schedule/data/CreateSemesterLessonData.ts
  src/v2/api/schedule/data/CreateTemporaryLessonData.ts
  src/v2/api/schedule/data/StaticLessonData.ts
  src/v2/api/schedule/data/TemporaryLessonData.ts
  src/v2/api/schedule/dto/CreateDateDTO.ts
  src/v2/api/schedule/dto/CreateLessonDTO.ts
  src/v2/api/schedule/dto/FortnightInfoAdaptor.ts
  src/v2/api/schedule/dto/FullLessonDTO.ts
  src/v2/api/schedule/dto/UpdateDynamicInfoDTO.ts
  src/v2/api/schedule/dto/UpdateStaticInfoDTO.ts
  src/v2/api/user/StudentRepository.ts
  src/v2/database/PrismaModule.ts
  src/v2/security/group-guard/GroupBySemesterLessonGuard.ts
  src/v2/security/group-guard/GroupByTemporaryLessonGuard.ts
  src/v2/utils/parser/RozParser.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: feature, migration, refactoring

#322 refactoring #280: refactored question repository
  src/v2/api/poll/DbQuestionWithAnswers.ts
  src/v2/api/poll/DbQuestionWithRoles.ts
  src/v2/api/poll/PollController.ts
  src/v2/api/poll/PollModule.ts
  src/v2/api/poll/PollService.ts
  src/v2/api/poll/QuestionAnswerRepository.ts
  src/v2/api/poll/QuestionMapper.ts
  src/v2/api/poll/QuestionRepository.ts
  src/v2/api/poll/dto/UpdateQuestionWithRolesDTO.ts
  src/v2/api/poll/pipe/QuestionByIdPipe.ts
  src/v2/api/poll/pipe/QuestionByRoleAndIdPipe.ts
  src/v2/api/teacher/DbDisciplineTeacher.ts
  src/v2/api/teacher/DbQuestion.ts
  src/v2/api/teacher/DisciplineTeacherRepository.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherService.ts
Labels: refactoring

#337 refactoring #302: refactored teacher initials function to use teacher repository
  src/v2/utils/parser/RozParser.ts
Labels: refactoring

#338 migration #333: updated question display enum
  prisma/migrations/20230516122056_update_question_display/migration.sql
  prisma/schema.prisma
  src/v2/api/teacher/TeacherService.ts
Labels: enhancement, migration

#340 feature #334: created event repository
  src/v2/database/PrismaModule.ts
  src/v2/database/entities/DbEvent.ts
  src/v2/database/repositories/EventRepository.ts
Labels: feature

#339 enhancement #289: added validation answers by value
  src/v2/api/teacher/DisciplineTeacherController.ts
  src/v2/api/teacher/pipe/QuestionAnswersValidationPipe.ts
  src/v2/utils/exceptions/InvalidValueException.ts
Labels: enhancement

#346 Add query logic and access to getDiscipline method
  src/v2/api/teacher/DisciplineTeacherController.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/utils/DatabaseUtils.ts
Labels: enhancement

#345 bugfix #344: amend issue 282
  src/v2/api/group/GroupController.ts
  src/v2/api/group/GroupService.ts
  src/v2/utils/exceptions/AbsenceOfCaptainException.ts
Labels: bug

#355 bugfix #354: updated ubuntu
  .github/workflows/deployment-master.yml
  .gitignore
Labels: bug

#358 testing: prepared repository for testing
  .github/workflows/build.yml
  Dockerfile
  package.json
  yarn.lock
Labels: packages, testing

#365 feature #233: added inheritance of roles and tests for permission
  prisma/migrations/20230527105135_role_inheritance/migration.sql
  prisma/schema.prisma
  src/v2/api/controllers/RoleController.ts
  src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
  src/v2/api/services/PermissionService.spec.ts
  src/v2/api/services/PermissionService.ts
  src/v2/api/services/RoleService.spec.ts
  src/v2/api/services/RoleService.ts
  src/v2/database/entities/DbRole.ts
  src/v2/database/repositories/RoleRepository.ts
  src/v2/modules/UserModule.ts
Labels: feature, migration, testing

#372 testing #359: added tests for returning marks
  src/v2/api/services/TeacherService.spec.ts
  src/v2/api/services/TeacherService.ts
Labels: testing

#373 testing #364: created unit tests for question mapper
  src/v2/mappers/QuestionMapper.spec.ts
  src/v2/mappers/QuestionMapper.ts
Labels: testing
