Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-07, with the labels that each got.

#519 bugfix #460: added correct sorting of teachers
  src/v2/api/dtos/OrderQAParam.ts
  src/v2/api/dtos/QueryAllTeacherDTO.ts
  src/v2/api/dtos/SortQATParam.ts
  src/v2/api/services/TeacherService.ts
  src/v2/database/DatabaseUtils.ts
  src/v2/mappers/TeacherMapper.ts
Labels: bug

#514 bugfix #509: fixed rating pagination
  src/v2/api/services/SubjectService.ts
  src/v2/api/services/TeacherService.spec.ts
  src/v2/api/services/TeacherService.ts
  src/v2/database/entities/DbDisciplineTeacherWithAnswers.ts
  src/v2/database/repositories/TeacherRepository.ts
  src/v2/mappers/QuestionMapper.ts
Labels: bug

#520 feature #472: added group changing endpoint
  src/v2/api/controllers/UserController.ts
  src/v2/api/responses/RoleWithStudentResponse.ts
  src/v2/api/responses/StudentResponse.ts
  src/v2/api/responses/UserResponse.ts
  src/v2/api/services/UserService.ispec.ts
  src/v2/api/services/UserService.ts
Labels: feature

#534 documentation #531: added documentation for some endpoints
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/responses/GeneralEventResponse.ts
Labels: documentation

#523 enhancement #485: moved endpoint for selective disciplines to the use…
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/services/DisciplineService.ispec.ts
  src/v2/api/services/DisciplineService.ts
  src/v2/api/services/UserService.ispec.ts
  src/v2/api/services/UserService.ts
Labels: enhancement

#537 bugfix #536: fixed rating pagination
  package.json
  prisma/migrations/20230707112910_add_rating_to_teacher/migration.sql
  prisma/schema.prisma
  src/v2/AppModule.ts
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/dtos/SortQATParam.ts
  src/v2/api/responses/PaginatedTeachersResponse.ts
  src/v2/api/responses/TeacherResponse.ts
  src/v2/api/responses/TeacherWithRatingResponse.ts
  src/v2/api/responses/TeacherWithSubjectResponse.ts
  src/v2/api/services/TeacherService.ts
  src/v2/database/entities/DbTeacher.ts
  src/v2/mappers/TeacherMapper.ts
  yarn.lock
Labels: bug, migration

#533 enhancement #484: added tests and documentation for group changing
  src/v2/api/controllers/UserController.ts
  src/v2/api/dtos/GroupRequestDTO.ts
  src/v2/api/services/UserService.ispec.ts
Labels: enhancement

#535 documentation #530: added Swagger documentation to Group endpoints
  src/v2/api/controllers/GroupController.ts
  src/v2/api/dtos/CreateGroupDTO.ts
  src/v2/api/dtos/UpdateGroupDTO.ts
  src/v2/api/responses/GroupResponse.ts
  src/v2/utils/QueryAllDTO.ts
Labels: documentation

#550 migration #549: made url and description fields nullable
  prisma/migrations/20230712133537_make_url_and_description_fields_nullable/migration.sql
  prisma/schema.prisma
Labels: migration

#540 feature #483: added captain changing endpoint
  src/v2/api/controllers/RoleController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/dtos/GiveRoleDTO.ts
  src/v2/api/dtos/TransferRoleDto.ts
  src/v2/api/services/RoleService.spec.ts
  src/v2/api/services/RoleService.ts
  src/v2/api/services/UserService.ispec.ts
  src/v2/api/services/UserService.ts
  src/v2/database/entities/DbRole.ts
  src/v2/mappers/RoleMapper.ts
Labels: feature

#562 migration #558: updated teacher roles
  prisma/migrations/20230719124959_update_teacher_roles/migration.sql
  prisma/schema.prisma
Labels: migration

#563 documentation #526: No parameters in Swagger
  src/v2/api/controllers/DateController.ts
Labels: documentation

#565 feature #545: implemented endpoint for event creating
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/AttachLessonDTO.ts
  src/v2/api/dtos/CreateEventDTO.ts
  src/v2/api/dtos/TeacherRoleAdapter.ts
  src/v2/api/pipes/AvatarValidationPipe.ts
  src/v2/api/responses/EventResponse.ts
  src/v2/api/services/ScheduleService.spec.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/mappers/ScheduleMapper.ts
  src/v2/utils/ArrayUtil.spec.ts
  src/v2/utils/ArrayUtil.ts
  src/v2/utils/exceptions/InvalidDateException.ts
  src/v2/utils/exceptions/ObjectIsRequiredException.ts
Labels: feature

#566 enhancement #555: improved endpoint for displaying teachers in a specific discipline
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/controllers/GroupController.ts
  src/v2/api/responses/DisciplineTeacherResponse.ts
  src/v2/api/responses/DisciplineTeachersResponse.ts
  src/v2/api/responses/TeacherWithContactAndRoleResponse.ts
  src/v2/api/services/DisciplineService.ts
  src/v2/api/services/SubjectService.ispec.ts
  src/v2/mappers/DisciplineTeacherMapper.ts
Labels: enhancement

#567 migration #552: created telegram group table
  prisma/migrations/20230724214645_add_telegram_group/migration.sql
  prisma/schema.prisma
Labels: migration

#569 feature #568: created study contract object
  .env.example
  src/v2/api/dtos/StudyContractDTO.ts
  src/v2/api/dtos/StudyContractParams.ts
Labels: feature

#579 feature #578: implemented study contract service
  email/templates/message.hbs
  package.json
  src/v2/api/ApiModule.ts
  src/v2/api/controllers/DocumentController.ts
  src/v2/api/datas/EmailData.ts
  src/v2/api/dtos/StudyContractDTO.ts
  src/v2/api/services/DocumentService.ts
  src/v2/api/services/EmailService.ts
  src/v2/modules/DocumentModule.ts
  src/v2/utils/exceptions/ObjectIsRequiredException.ts
  src/v2/utils/files/FileService.ts
  yarn.lock
Labels: feature, packages

#581 feature #580: create tables for external API integration
  prisma/migrations/20230730170237_tables_for_external_api_integration/migration.sql
  prisma/schema.prisma
Labels: migration
