Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-10, with the labels that each got.

#758 enhancement #750: Improved updating avatar:
  src/v2/api/controllers/UserController.ts
  src/v2/api/services/UserService.ts
  src/v2/database/repositories/UserRepository.ts
  src/v2/utils/files/FileService.ts
Labels: enhancement

#770 bug #761: Reduced max avatar size:
  src/v2/api/controllers/UserController.ts
  src/v2/api/pipes/AvatarValidationPipe.ts
Labels: bug

#764 documentation #763: updated Swagger documentation for Discipline
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/dtos/CreateDisciplineDTO.ts
  src/v2/api/responses/DisciplineResponse.ts
  src/v2/api/responses/DisciplineTeacherResponse.ts
  src/v2/api/responses/DisciplineTeachersResponse.ts
  src/v2/api/responses/TeacherResponse.ts
  src/v2/api/services/DisciplineService.ts
  src/v2/security/Access.ts
Labels: documentation

#782 feature #751: added ability to delete avatars
  src/v2/api/controllers/UserController.ts
  src/v2/api/services/UserService.ts
  src/v2/mappers/UserMapper.ts
  src/v2/security/PERMISSION.ts
Labels: feature

#787 bugfix #786: fixed email verification
  src/v2/api/services/AuthService.ts
Labels: bug

#777 documentation #765: added documentation to user endpoints
  src/v2/api/controllers/UserController.ts
  src/v2/api/datas/UpdateSuperheroData.ts
  src/v2/api/dtos/ApproveDTO.ts
  src/v2/api/dtos/CreateSuperheroDTO.ts
  src/v2/api/dtos/GroupRequestDTO.ts
  src/v2/api/dtos/UpdateSuperheroDTO.ts
  src/v2/api/responses/DisciplineResponse.ts
  src/v2/api/responses/GroupResponse.ts
  src/v2/api/responses/PaginationDataResponse.ts
  src/v2/api/responses/SelectiveBySemestersResponse.ts
  src/v2/api/responses/StudentResponse.ts
  src/v2/api/responses/SuperheroResponse.ts
  src/v2/api/responses/VerifySuperheroResponse.ts
  src/v2/api/services/UserService.ts
  src/v2/database/repositories/SuperheroRepository.ts
  src/v2/mappers/StudentMapper.ts
  src/v2/security/Access.ts
  src/v2/utils/documentation/decorators.ts
Labels: documentation

#776 bugfix #769: fixed update start time of no period events
  src/v2/api/services/ScheduleService.ts
Labels: bug

#780 migration #775 and bug #783: Added postInfo field in TelegramGroup:
  prisma/migrations/20231005145714_add_post_info_to_telegramgroup/migration.sql
  prisma/schema.prisma
  src/v2/api/controllers/TelegramGroupController.ts
  src/v2/api/dtos/CreateTelegramGroupDTO.ts
  src/v2/api/dtos/UpdateTelegramGroupDTO.ts
  src/v2/api/responses/GroupsWithTelegramGroupsResponse.ts
  src/v2/api/responses/TelegramGroupByTelegramIdResponse.ts
  src/v2/api/responses/TelegramGroupResponse.ts
  src/v2/api/services/TelegramGroupService.ts
  src/v2/database/entities/DbTelegramGroup.ts
  src/v2/mappers/GroupMapper.ts
  src/v2/mappers/TelegramGroupMapper.ts
Labels: migration

#760 enhancement #744: Automated index calculation
  src/v2/utils/parser/ScheduleParser.ts
Labels: enhancement

#778 enhancement #725: Updated roz.kpi.ua parser
  src/v2/utils/parser/RozParser.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: enhancement

#790 enhancement #771: Improved and merged endpoints for captain changing:
  src/v2/api/controllers/GroupController.ts
  src/v2/api/dtos/SwitchCaptainDTO.ts
  src/v2/api/services/GroupService.ispec.ts
  src/v2/api/services/GroupService.ts
  src/v2/api/services/UserService.ts
  src/v2/mappers/StudentMapper.ts
  src/v2/security/permission-guard/PermissionGuard.ts
  src/v2/utils/exceptions/StudentIsAlreadyCaptainException.ts
Labels: enhancement

#762 feature #746: Add ability to leave group
  src/v2/api/controllers/GroupController.ts
  src/v2/api/services/GroupService.ts
  src/v2/security/PERMISSION.ts
Labels: feature
