Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-01, with the labels that each got.

#51 feature/updating-scheme-3
  prisma/schema.prisma
Labels: feature

#52 feature/schedule-parser
  src/v2/utils/parser/Parser.ts
  src/v2/utils/parser/ParserModule.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: feature

#53 feature/new-exceptions
  src/v2/utils/exceptions/ActionGroupForbiddenException.ts
  src/v2/utils/exceptions/InvalidGroupIdException.ts
  src/v2/utils/exceptions/InvalidLessonIdException.ts
  src/v2/utils/exceptions/InvalidSubjectIdException.ts
Labels: feature

#54 feature/adding-new-guards
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/group/GroupByIdPipe.ts
  src/v2/api/group/GroupController.ts
  src/v2/api/schedule/ScheduleRepository.ts
  src/v2/security/JwtStrategy.ts
  src/v2/security/group-guard/GroupByLessonGuard.ts
  src/v2/security/group-guard/GroupByParamsGuard.ts
  src/v2/security/group-guard/GroupBySemesterLessonGuard.ts
  src/v2/security/group-guard/GroupByTemporaryLessonGuard.ts
  src/v2/security/group-guard/GroupGuard.ts
Labels: feature

#55 feature/schedule-endpoints-1
  src/v2/api/group/GroupModule.ts
  src/v2/api/schedule/ScheduleController.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/schedule/dto/FortnightInfoAdaptor.ts
  src/v2/api/schedule/dto/FullLessonDTO.ts
  src/v2/api/schedule/dto/StaticLessonInfo.ts
  src/v2/api/schedule/dto/TemporaryLessonInfo.ts
  src/v2/api/schedule/dto/UpdateDynamicInfoDTO.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/config/Configuration.ts
  src/v2/utils/date/DateModule.ts
  src/v2/utils/date/DateService.ts
Labels: feature

#56 feature/enhancement
  src/v2/api/schedule/ScheduleModule.ts
  src/v2/api/subject/SubjectByIdPipe.ts
  src/v2/api/subject/SubjectController.ts
  src/v2/api/teacher/dto/GetDTO.ts
  src/v2/security/TelegramGuard.ts
Labels: enhancement

#57 feature/schedule-endpoints-2
  prisma/schema.prisma
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/schedule/ScheduleController.ts
  src/v2/api/schedule/ScheduleRepository.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/schedule/dto/CreateDateDTO.ts
  src/v2/api/schedule/dto/CreateLessonDTO.ts
  src/v2/api/schedule/dto/CreateSemesterLessonData.ts
  src/v2/api/schedule/dto/CreateTemporaryLessonData.ts
  src/v2/api/schedule/dto/UpdateStaticInfoDTO.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/teacher/dto/CreateDisciplineTeacherData.ts
  src/v2/api/teacher/dto/TeacherRoleAdapter.ts
Labels: feature

#58 Get discipline teachers
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherService.ts
Labels: feature

#59 feature/verify-superhero
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserService.ts
Labels: feature

#60 feature/selective-disciplines
  src/v2/api/discipline/DisciplineController.ts
  src/v2/api/discipline/DisciplineModule.ts
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/dto/ApproveDTO.ts
  src/v2/security/group-guard/GroupByDisciplineGuard.ts
Labels: feature

#61 feature/permissions
  src/v2/api/user/UserService.ts
  src/v2/api/user/dto/CreateSuperheroDTO.ts
  src/v2/security/group-guard/GroupGuard.ts
  src/v2/security/permission-guard/GlobalPermissionGuard.ts
  src/v2/security/permission-guard/GroupPermissionGuard.ts
  src/v2/security/permission-guard/Permission.ts
  src/v2/security/permission-guard/PermissionGuard.ts
  src/v2/utils/exceptions/NoPermissionException.ts
Labels: feature

#62 feature/pagination-search-sorting
  src/v2/api/group/GroupController.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/subject/SubjectController.ts
  src/v2/api/subject/SubjectService.ts
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/teacher/dto/GetDTO.ts
  src/v2/api/utils/DatabaseUtils.ts
  src/v2/api/utils/dto/PageDTO.ts
  src/v2/api/utils/dto/SearchDTO.ts
  src/v2/api/utils/dto/SortDTO.ts
Labels: feature

#63 feature/bugfix
  src/v2/api/group/GroupService.ts
Labels: bug

#65 feature/updating-scheme-4
  prisma/migrations/20230116092156_init/migration.sql
  prisma/migrations/20230116094723_add_discipline_teacher_roles/migration.sql
  prisma/migrations/20230117075206_add_discipline_to_teacher/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/v2/api/discipline/DisciplineRepository.ts
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/discipline/DisciplineTypeRepository.ts
  src/v2/api/discipline/DisciplineTypeService.ts
  src/v2/api/discipline/dto/CreateDisciplineDTO.ts
  src/v2/api/group/GroupController.ts
  src/v2/api/group/GroupRepository.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/subject/SubjectRepository.ts
  src/v2/api/teacher/DisciplineTeacherRepository.ts
  src/v2/api/teacher/DisciplineTeacherRoleRepository.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherRepository.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/teacher/dto/CreateDisciplineTeacherData.ts
  src/v2/api/teacher/dto/CreateDisciplineTeacherRoleData.ts
  src/v2/database/PrismaModule.ts
  src/v2/utils/parser/ParserModule.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: feature

#68 feature/roles-and-rights
  Dockerfile
  prisma/migrations/20230121185611_update_roles/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/v2/api/group/GroupModule.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/schedule/ScheduleModule.ts
  src/v2/api/subject/SubjectController.ts
  src/v2/api/subject/SubjectModule.ts
  src/v2/api/subject/SubjectRepository.ts
  src/v2/api/subject/SubjectService.ts
  src/v2/api/user/StudentRepository.ts
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/dto/CreateRoleDTO.ts
  src/v2/api/user/dto/GiveRoleDTO.ts
  src/v2/api/user/grant/GrantController.ts
  src/v2/api/user/grant/GrantRepository.ts
  src/v2/api/user/grant/GrantService.ts
  src/v2/api/user/grant/dto/UpdateGrantDTO.ts
  src/v2/api/user/role/RoleController.ts
  src/v2/api/user/role/RoleRepository.ts
  src/v2/api/user/role/RoleService.ts
  src/v2/api/user/role/dto/UpdateRoleDTO.ts
  src/v2/database/PrismaModule.ts
  src/v2/security/permission-guard/GlobalPermissionGuard.ts
  src/v2/security/permission-guard/GroupPermissionGuard.ts
  src/v2/security/permission-guard/PermissionGuard.ts
  src/v2/utils/RequestUtils.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  yarn.lock
Labels: feature

#69 feature/reset-password
  src/v2/AppModule.ts
  src/v2/api/auth/AuthController.ts
  src/v2/api/auth/AuthModule.ts
  src/v2/api/auth/AuthService.ts
  src/v2/api/auth/dto/ForgotPasswordDTO.ts
  src/v2/api/auth/dto/ResetPasswordDTO.ts
  src/v2/utils/exceptions/InvalidResetTokenException.ts
  src/v2/utils/exceptions/TooManyActionsException.ts
Labels: feature

#83 bugfix/database-utils
  src/v2/api/utils/DatabaseUtils.ts
  src/v2/utils/QueryAllDTO.ts
Labels: bug

#86 CRUD system for subjects
  .gitignore
  src/v2/api/subject/SubjectByIdPipe.ts
  src/v2/api/subject/SubjectController.ts
  src/v2/api/subject/SubjectRepository.ts
  src/v2/api/subject/SubjectService.ts
  src/v2/api/subject/dto/CreateSubjectDTO.ts
  src/v2/api/subject/dto/SubjectFieldsDTO.ts
  src/v2/api/subject/dto/UpdateSubjectDTO.ts
Labels: documentation, feature

#84 feature/new-dtos
  src/v2/api/auth/AuthController.ts
  src/v2/api/poll/PollController.ts
  src/v2/api/user/UserController.ts
Labels: documentation, feature

#92 bugfix/update-poles
  prisma/migrations/20230121185611_update_roles/migration.sql
Labels: bug

#97 added CRUD system for teachers and their contacts
  .gitignore
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherRepository.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/teacher/dto/ContactByNamePipe.ts
  src/v2/api/teacher/dto/CreateContactDTO.ts
  src/v2/api/teacher/dto/CreateContactData.ts
  src/v2/api/teacher/dto/CreateTeacherDTO.ts
  src/v2/api/teacher/dto/GetDTO.ts
  src/v2/api/teacher/dto/TeacherByIdPipe.ts
  src/v2/api/teacher/dto/UpdateContactDTO.ts
  src/v2/api/teacher/dto/UpdateTeacherDTO.ts
  src/v2/utils/QueryAllDTO.ts
  src/v2/utils/exceptions/InvalidContactNameException.ts
  src/v2/utils/exceptions/InvalidEntityIdException.ts
Labels: documentation, feature

#107 feature/whitelist-dtos
  src/main.ts
  src/v2/utils/QueryAllDTO.ts
Labels: enhancement

#108 feature/captain-role-management
  prisma/migrations/20230125150451_nullable_username_and_password/migration.sql
  prisma/migrations/20230126093938_nullable_first_and_last_names/migration.sql
  prisma/schema.prisma
  src/v2/api/group/GroupController.ts
  src/v2/api/group/GroupRepository.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/group/dto/EmailDTO.ts
  src/v2/api/group/dto/RoleDTO.ts
  src/v2/api/user/StudentRepository.ts
  src/v2/api/user/UserByIdPipe.ts
  src/v2/api/user/UserRepository.ts
  src/v2/api/user/dto/CreateUserData.ts
  src/v2/api/user/dto/СreateStudentData.ts
Labels: documentation, feature

#115 feature/add-category-and-description
  prisma/migrations/20230128143123_add_category_and_description/migration.sql
  prisma/schema.prisma
Labels: migration

#116 feature/change-telegramid-type
  prisma/migrations/20230128144030_convert_datatype_of_telegramid/migration.sql
  prisma/schema.prisma
  src/v2/api/auth/AuthService.ts
  src/v2/api/teacher/dto/CreateTeacherDTO.ts
Labels: migration

#128 feature/checking-password-similarity
  src/v2/api/auth/AuthService.ts
  src/v2/utils/exceptions/PasswordRepeatException.ts
Labels: documentation, enhancement

#130 feature/check-state-due-authorization
  src/v2/api/auth/AuthService.ts
Labels: enhancement

#140 feature/crud-for-user-entities
  src/v2/api/auth/dto/RegistrationDTO.ts
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherRepository.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/user/ContactByUserIdPipe.ts
  src/v2/api/user/ContactRepository.ts
  src/v2/api/user/StudentRepository.ts
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserRepository.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/dto/CreateContactDTO.ts
  src/v2/api/user/dto/CreateContactData.ts
  src/v2/api/user/dto/UpdateContactDTO.ts
  src/v2/api/user/dto/UpdateContactData.ts
  src/v2/api/user/dto/UpdateStudentDTO.ts
  src/v2/api/user/dto/UpdateUserDTO.ts
  src/v2/api/user/dto/UpdateUserData.ts
  src/v2/database/PrismaModule.ts
Labels: documentation, feature

#143 bugfix/wrong-env-name
  src/v2/config/Configuration.ts
Labels: bug

#145 feature/cascade-deleting
  prisma/migrations/20230130204536_setting_delete_cascade/migration.sql
  prisma/schema.prisma
Labels: migration

#147 feature/check-captain-by-groupid
  src/v2/api/auth/AuthController.ts
  src/v2/api/auth/AuthModule.ts
  src/v2/api/auth/AuthService.ts
Labels: documentation, feature
