Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-06, with the labels that each got.

#377 Dockerfile
  Dockerfile
Labels: enhancement

#382 deployment #380: fix Dockerfile
  Dockerfile
Labels: bug

#381 testing #363: created unit tests for date service
  .testing.env
  src/v2/api/services/DisciplineTeacherService.ts
  src/v2/api/services/PollService.ts
  src/v2/utils/date/DateService.spec.ts
  src/v2/utils/date/DateService.ts
Labels: testing

#396 refactoring #393: moved endpoint to another path
  src/v2/api/controllers/DisciplineTeacherController.ts
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/services/DisciplineTeacherService.ts
  src/v2/api/services/TeacherService.ts
  src/v2/mappers/DisciplineTeacherMapper.ts
Labels: documentation, refactoring

#399 feature #394: connected swagger
  package-lock.json
  package.json
  src/main.ts
  src/v2/api/controllers/PollController.ts
  src/v2/api/dtos/CreateQuestionDTO.ts
  src/v2/api/dtos/CreateQuestionRoleDTO.ts
  src/v2/api/dtos/CreateQuestionWithRolesDTO.ts
  src/v2/api/dtos/UpdateQuestionDTO.ts
  src/v2/api/dtos/UpdateQuestionWithRolesDTO.ts
  src/v2/api/pipes/QuestionByRoleAndIdPipe.ts
  src/v2/api/responses/PollDisciplineTeachersResponse.ts
  src/v2/api/responses/QuestionWithRolesResponse.ts
  yarn.lock
Labels: documentation, feature

#411 bugfix #410: fixed access for teachers endpoint
  src/v2/api/controllers/TeacherController.ts
Labels: bug

#416 bugfix #415: fixed NODE_ENV error:
  package.json
  yarn.lock
Labels: bug, packages

#436 migration #430: created selective amount table
  prisma/migrations/20230616213512_add_selective_amounts/migration.sql
  prisma/schema.prisma
Labels: migration

#434 feature #397: created CDN to store user avatars
  Dockerfile
  package.json
  src/main.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/pipes/AvatarValidationPipe.ts
  src/v2/api/services/UserService.ts
  src/v2/modules/UserModule.ts
  src/v2/utils/exceptions/InvalidExtensionException.ts
  src/v2/utils/exceptions/TooLargeSizeException.ts
  src/v2/utils/files/FileModule.ts
  src/v2/utils/files/FileService.ts
  yarn.lock
Labels: feature

#424 testing #386: created integration tests for for subject service
  prisma/seed.ts
  src/v2/api/services/SubjectService.ispec.ts
Labels: testing

#439 enhancement #438: removed linebreak-style linter rule
  .eslintrc.cjs
Labels: enhancement, refactoring

#442 bugfix #440: fixed URL generation in user avatars
  src/v2/utils/files/FileService.ts
Labels: bug

#441 enhancement #437: updated logic of poll borders and semester dates:
  prisma/migrations/20230617093017_correct_semesters_date/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/v2/api/services/DisciplineTeacherService.ts
  src/v2/api/services/PollService.ts
  src/v2/utils/date/DateService.spec.ts
  src/v2/utils/date/DateService.ts
Labels: bug, enhancement, migration

#445 enhancement #412: moved semester definition in schedule parser
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/services/ScheduleService.spec.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/utils/parser/RozParser.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: enhancement

#420 testing #388: created tests for question service
  prisma/seed.ts
  src/v2/api/services/PollService.ispec.ts
Labels: testing

#452 feature #413: added checking subject selectiveness
  src/v2/database/repositories/DisciplineRepository.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: feature

#454 enhancement #450: changed response teacher object
  src/v2/api/services/TeacherService.ts
Labels: enhancement

#451 testing #389: Create integration tests for discipline teacher service
  src/v2/api/services/DisciplineTeacherService.ispec.ts
  src/v2/database/repositories/DisciplineTeacherRepository.ts
  src/v2/utils/date/DateService.ts
Labels: testing

#449 feature #446: returned only selected by user disciplines
  src/v2/api/controllers/PollController.ts
  src/v2/api/services/PollService.ispec.ts
  src/v2/api/services/PollService.ts
  src/v2/utils/date/DateService.ts
Labels: feature

#458 bugfix #457: fixed duplication disciplines after parsing
  src/v2/utils/parser/ScheduleParser.ts
Labels: bug

#459 bugfix #456: changed response of get discipline teacher endpoint
  src/v2/api/controllers/PollController.ts
  src/v2/api/responses/PollDisciplineTeachersResponse.ts
Labels: bug

#462 enhancement #447: added checker for selective disciplines
  src/v2/api/services/DisciplineTeacherService.ts
  src/v2/database/entities/DbStudent.ts
  src/v2/database/repositories/StudentRepository.ts
  src/v2/utils/exceptions/NotSelectedDisciplineException.ts
Labels: enhancement

#466 enhancement #464: updated getting discipline teachers
  src/v2/api/services/DisciplineTeacherService.ispec.ts
  src/v2/api/services/DisciplineTeacherService.ts
  src/v2/api/services/TeacherService.ts
  src/v2/utils/ArrayUtil.spec.ts
  src/v2/utils/ArrayUtil.ts
Labels: enhancement

#474 enhancement #469: removed empty teachers creation
  src/v2/utils/parser/ScheduleParser.ts
  src/v2/utils/parser/ScheduleParserTypes.ts
Labels: enhancement

#479 bugfix #455: fixed redundant teacher's role
  src/v2/api/services/TeacherService.ts
  src/v2/mappers/DisciplineTeacherMapper.ts
Labels: bug

#478 feature #468: created endpoint for semesters
  src/v2/api/controllers/DateController.ts
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/pipes/ConvertToBooleanPipe.ts
  src/v2/api/responses/SemesterResponse.ts
  src/v2/api/services/PollService.ts
  src/v2/utils/date/DateModule.ts
  src/v2/utils/date/DateService.ts
Labels: feature

#453 feature #427: created attach selective discipline endpoint
  package.json
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/controllers/GroupController.ts
  src/v2/api/dtos/AttachSelectiveDisciplinesDTO.ts
  src/v2/api/pipes/SelectiveDisciplinesPipe.ts
  src/v2/api/pipes/StudentPipe.ts
  src/v2/api/services/DisciplineService.ispec.ts
  src/v2/api/services/DisciplineService.ts
  src/v2/api/services/GroupService.ts
  src/v2/database/entities/DbGroup.ts
  src/v2/database/repositories/GroupRepository.ts
  src/v2/mappers/DisciplineMapper.ts
  src/v2/mappers/GroupMapper.ts
  src/v2/modules/MapperModule.ts
  src/v2/utils/exceptions/AlreadySelectedException.ts
  src/v2/utils/exceptions/ExcessiveSelectiveDisciplinesException.ts
  src/v2/utils/exceptions/NotApprovedException.ts
  src/v2/utils/exceptions/NotBelongToGroupException.ts
  src/v2/utils/exceptions/NotSelectiveException.ts
Labels: feature

#488 enhancement #463: returned rating of teachers
  src/v2/api/controllers/SubjectController.ts
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/dtos/QueryAllTeacherDTO.ts
  src/v2/api/responses/SubjectWithTeachersResponse.ts
  src/v2/api/responses/TeacherWithRatingAndRolesResponse.ts
  src/v2/api/responses/TeacherWithRatingResponse.ts
  src/v2/api/responses/TeachersWithRatingResponse.ts
  src/v2/api/services/SubjectService.ispec.ts
  src/v2/api/services/SubjectService.ts
  src/v2/api/services/TeacherService.spec.ts
  src/v2/api/services/TeacherService.ts
  src/v2/mappers/TeacherMapper.ts
  src/v2/modules/SubjectModule.ts
Labels: enhancement

#480 feature #473: added endpoint for user's selective disciplines
  src/v2/api/controllers/DateController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/responses/SelectiveBySemestersResponse.ts
  src/v2/api/responses/SemesterResponse.ts
  src/v2/api/services/UserService.ispec.ts
  src/v2/api/services/UserService.ts
  src/v2/mappers/DisciplineMapper.ts
Labels: feature

#498 enhancement #495: returned rating of teachers
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/responses/ContactsResponse.ts
  src/v2/api/responses/TeacherWithContactsResponse.ts
  src/v2/api/responses/TeacherWithSubjectResponse.ts
  src/v2/api/services/TeacherService.ts
Labels: enhancement

#497 feature #493: added cathedra
  prisma/migrations/20230625170535_add_cathedras_and_teachers_on_cathedras/migration.sql
  prisma/schema.prisma
  src/v2/api/ApiModule.ts
  src/v2/api/controllers/CathedraController.ts
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/dtos/CreateCathedraDTO.ts
  src/v2/api/pipes/CathedraByIdPipe.ts
  src/v2/api/responses/CathedraResponse.ts
  src/v2/api/responses/CathedraWithTeachersResponse.ts
  src/v2/api/responses/ContactResponse.ts
  src/v2/api/responses/TeacherWithRolesAndContactsResponse.ts
  src/v2/api/services/CathedraService.ts
  src/v2/api/services/TeacherService.ts
  src/v2/database/entities/DbTeacher.ts
  src/v2/database/repositories/CathedraRepository.ts
  src/v2/database/repositories/TeacherRepository.ts
  src/v2/modules/CathedraModule.ts
  src/v2/modules/PrismaModule.ts
Labels: feature, migration

#496 Enhancement/add pagination of teacher comments
  src/v2/api/dtos/CommentsQueryDTO.ts
  src/v2/api/pipes/QuestionAnswersValidationPipe.ts
  src/v2/api/services/PollService.ispec.ts
  src/v2/api/services/PollService.ts
Labels: enhancement

#512 enhancement #510: increased the character validation limit
  src/v2/api/pipes/QuestionAnswersValidationPipe.ts
Labels: enhancement
