Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-02, with the labels that each got.

#161 Send captain telegram id with verification
  src/v2/api/auth/AuthService.ts
  src/v2/api/group/GroupService.ts
  src/v2/telegram/dto/VerifyStudentDTO.ts
Labels: feature

#159 bug/user-crud-dto-refactor
  src/v2/api/user/dto/CreateContactDTO.ts
  src/v2/api/user/dto/UpdateContactDTO.ts
  src/v2/api/user/dto/UpdateStudentDTO.ts
  src/v2/api/user/dto/UpdateUserDTO.ts
Labels: bug

#172 Check reset token
  src/v2/api/auth/AuthController.ts
  src/v2/api/auth/AuthService.ts
Labels: feature

#174 Renamed groupRole pole in prisma.schema
  prisma/schema.prisma
  src/v2/api/group/GroupRepository.ts
  src/v2/api/group/dto/GroupFieldsDTO.ts
Labels: enhancement, migration

#176 improving-ukrainian-regex
  src/v2/api/auth/dto/RegistrationDTO.ts
  src/v2/api/group/dto/CreateGroupDTO.ts
  src/v2/api/group/dto/UpdateGroupDTO.ts
  src/v2/api/poll/dto/QuestionByIdPipe.ts
  src/v2/api/poll/dto/UpdateRoleParam.ts
  src/v2/api/subject/dto/CreateSubjectDTO.ts
  src/v2/api/subject/dto/UpdateSubjectDTO.ts
  src/v2/api/teacher/dto/CreateTeacherDTO.ts
  src/v2/api/teacher/dto/UpdateTeacherDTO.ts
  src/v2/api/user/dto/CreateContactDTO.ts
  src/v2/api/user/dto/UpdateContactDTO.ts
  src/v2/api/user/dto/UpdateStudentDTO.ts
  src/v2/api/user/dto/UpdateUserDTO.ts
  src/v2/utils/GLOBALS.ts
Labels: bug, enhancement

#190 migration/added-user-role
  prisma/migrations/20230211120924_new_role_name/migration.sql
  prisma/schema.prisma
Labels: migration

#198 give base user role for user
  src/v2/api/auth/AuthModule.ts
  src/v2/api/auth/AuthService.ts
  src/v2/api/auth/dto/RegistrationDTO.ts
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/role/RoleService.ts
Labels: feature

#199 Default middle name
  prisma/migrations/20230213225347_default_middle_name/migration.sql
  prisma/schema.prisma
Labels: migration

#202 migration/contact-refactor
  prisma/migrations/20230216203518_contact_refactor/migration.sql
  prisma/schema.prisma
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/user/ContactRepository.ts
  src/v2/api/user/dto/CreateContactDTO.ts
  src/v2/api/user/dto/CreateContactData.ts
  src/v2/api/user/dto/UpdateContactData.ts
Labels: migration

#207 Added Data files
  src/v2/api/subject/SubjectRepository.ts
  src/v2/api/subject/SubjectService.ts
  src/v2/api/subject/data/CreateSubjectData.ts
  src/v2/api/subject/data/UpdateSubjectData.ts
Labels: enhancement

#209 feature/contact-refactor
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/dto/CreateContactDTO.ts
  src/v2/api/user/dto/UpdateContactDTO.ts
  src/v2/api/user/dto/UpdateContactData.ts
Labels: feature

#216 Added
  prisma/migrations/20230220214320_question_display/migration.sql
  prisma/migrations/20230220215601_question_display2/migration.sql
  prisma/migrations/20230220215953_question_display2/migration.sql
  prisma/schema.prisma
  src/v2/api/teacher/DisciplineTeacherRepository.ts
Labels: migration

#221 refactoring/update-exception-handler
  src/main.ts
  src/v2/security/exception-handler/CommonExceptions.ts
  src/v2/security/exception-handler/LoggerCore.ts
Labels: refactoring

#213 Added marks
  src/v2/api/auth/AuthModule.ts
  src/v2/api/poll/dto/CreateQuestionDTO.ts
  src/v2/api/poll/dto/UpdateQuestionDTO.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherRepository.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/teacher/data/MarksData.ts
  src/v2/api/teacher/dto/CreateAnswersDTO.ts
  src/v2/api/teacher/query/MarksQueryDTO.ts
  src/v2/utils/exceptions/InvalidContactNameException.ts
  src/v2/utils/exceptions/InvalidQueryException.ts
Labels: enhancement, feature

#222 Added get teachers method for poll
  src/v2/api/discipline/DisciplineModule.ts
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/group/GroupModule.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/poll/PollController.ts
  src/v2/api/poll/PollModule.ts
  src/v2/api/poll/PollService.ts
  src/v2/api/teacher/TeacherModule.ts
  src/v2/api/user/StudentRepository.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/UserService.ts
Labels: feature

#227 feature/add-checking-of-responses-about-teachers
  src/v2/api/poll/PollController.ts
  src/v2/api/poll/QuestionAnswerRepository.ts
  src/v2/api/poll/dto/ResponseDTO.ts
  src/v2/api/teacher/DisciplineTeacherController.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherModule.ts
  src/v2/telegram/TelegramAPI.ts
  src/v2/telegram/dto/VerifyResponseDTO.ts
  src/v2/utils/ArrayUtil.ts
Labels: feature

#231 feature/teacher-subjects
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherRepository.ts
  src/v2/api/teacher/TeacherService.ts
Labels: feature

#234 feature/update-telegram-registration
  src/v2/api/auth/AuthController.ts
  src/v2/api/auth/AuthService.ts
  src/v2/api/auth/dto/RegisterTelegramDTO.ts
Labels: feature

#235 Enhancement/group guards
  src/v2/AppModule.ts
  src/v2/api/ApiModule.ts
  src/v2/api/discipline/DisciplineController.ts
  src/v2/api/discipline/DisciplineModule.ts
  src/v2/api/discipline/DisciplineRepository.ts
  src/v2/api/discipline/DisciplineService.ts
  src/v2/api/discipline/DisciplineTypeService.ts
  src/v2/api/group/GroupController.ts
  src/v2/api/group/GroupModule.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/group/pipe/GroupByIdPipe.ts
  src/v2/api/poll/PollController.ts
  src/v2/api/poll/PollModule.ts
  src/v2/api/poll/PollService.ts
  src/v2/api/resources/ResourceModule.ts
  src/v2/api/schedule/ScheduleController.ts
  src/v2/api/schedule/ScheduleModule.ts
  src/v2/api/schedule/ScheduleRepository.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/subject/SubjectModule.ts
  src/v2/api/subject/SubjectService.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherController.ts
  src/v2/api/teacher/TeacherModule.ts
  src/v2/api/teacher/TeacherService.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/grant/GrantService.ts
  src/v2/api/user/role/RoleService.ts
  src/v2/database/PrismaModule.ts
  src/v2/security/AccessModule.ts
  src/v2/security/PermissionService.ts
  src/v2/security/group-guard/GroupByLessonGuard.ts
  src/v2/security/group-guard/GroupBySemesterLessonGuard.ts
  src/v2/security/group-guard/GroupByTemporaryLessonGuard.ts
  src/v2/security/group-guard/GroupGuard.ts
  src/v2/security/permission-guard/PermissionGuard.ts
  src/v2/utils/date/DateModule.ts
Labels: enhancement, refactoring

#238 Added access decorator
  src/v2/api/discipline/DisciplineController.ts
Labels: refactoring

#236 add group-roles
  src/v2/api/group/GroupRepository.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/dto/ApproveDTO.ts
  src/v2/security/AccessModule.ts
Labels: feature

#243 feature/link-telegram
  src/v2/api/auth/AuthService.ts
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserService.ts
Labels: enhancement, feature

#240 Fixed code
  src/v2/api/group/GroupService.ts
Labels: refactoring

#247 fix/delete-user-role
  src/v2/api/auth/dto/TelegramDTO.ts
  src/v2/api/user/UserRepository.ts
  src/v2/api/user/UserService.ts
Labels: bug, enhancement

#249 enhancement/add-role-to-user-object
  src/v2/api/group/GroupService.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/data/StudentDTOs.ts
Labels: enhancement

#254 fix/delete-ascii-checking
  src/v2/api/user/dto/CreateContactDTO.ts
  src/v2/api/user/dto/UpdateContactDTO.ts
Labels: bug
