Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-09, with the labels that each got.

#663 bugfix #662: fixed receiving of endTime in update event endpoint
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/UpdateEventDTO.ts
  src/v2/api/services/ScheduleService.ts
Labels: bug

#675 bugfix #674: fixed email re-verification
  src/v2/api/services/AuthService.ts
Labels: bug

#667 enhancement #666: improved /groups/{groupId}/disciplineTeachers route:
  src/v2/api/controllers/GroupController.ts
  src/v2/api/services/GroupService.ts
  src/v2/utils/date/DateService.ts
Labels: enhancement

#681 bugfix #668: fixed deleting discipline teachers
  src/v2/api/services/ScheduleService.ts
Labels: bug

#673 bugfix #643: fixed bug with events getting
  src/v2/api/services/ScheduleService.spec.ts
  src/v2/api/services/ScheduleService.ts
Labels: bug

#686 bugfix #676: bug with login through Telegram
  src/v2/api/controllers/AuthController.ts
  src/v2/api/services/AuthService.ts
Labels: bug

#694 bugfix #693: fixed Axios Error
  src/v2/api/services/ScheduleService.ts
  src/v2/api/services/UserService.ts
Labels: bug

#701 bugfix #690: fixed bug with search for selective discipline
  src/v2/api/services/UserService.ispec.ts
  src/v2/api/services/UserService.ts
  src/v2/modules/UserModule.ts
  src/v2/telegram/TelegramAPI.ts
Labels: bug

#700 enhancement #677: improved /v2/users/{userId}/group/{groupId} route:
  src/v2/api/services/GroupService.ts
  src/v2/api/services/UserService.ts
  src/v2/modules/UserModule.ts
Labels: bug, enhancement

#657 feature #640: Added endpoint to check permissions
  src/v2/api/ApiModule.ts
  src/v2/api/controllers/PermissionController.ts
  src/v2/api/dtos/CheckPermissionsDTO.ts
  src/v2/api/pipes/UserByIdPipe.ts
  src/v2/api/responses/CheckPermissionsResponse.ts
  src/v2/api/services/PermissionService.ispec.ts
  src/v2/api/services/PermissionService.spec.ts
  src/v2/api/services/PermissionService.ts
  src/v2/modules/PermissionModule.ts
Labels: feature

#720 bugfix #717: fixed bug with the calculation of the last end date
  src/v2/api/services/ScheduleService.ts
  src/v2/utils/parser/ScheduleParser.ts
Labels: bug

#718 migration #678: created updatedAt and createdAt fields
  prisma/migrations/20230909141500_created_and_updated_fields/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/v2/api/services/DisciplineTeacherService.ispec.ts
  src/v2/api/services/GroupService.ispec.ts
  src/v2/api/services/SubjectService.ts
  src/v2/api/services/TeacherService.ts
  src/v2/api/services/UserService.ispec.ts
  src/v2/database/entities/DbStudent.ts
  src/v2/database/repositories/StudentRepository.ts
  src/v2/database/repositories/TeacherRepository.ts
Labels: migration

#705 testing #647: Implement integration tests for methods of getting events
  src/v2/api/services/ScheduleService.ispec.ts
  src/v2/api/services/ScheduleService.spec.ts
Labels: testing

#703 enhancement #672: Changed user contacts endpoints logic
  src/v2/api/controllers/UserController.ts
  src/v2/api/pipes/ContactByUserIdPipe.ts
  src/v2/api/services/UserService.ts
  src/v2/database/repositories/ContactRepository.ts
Labels: enhancement

#721 bugfix #719: added check for the existence of captain
  src/v2/api/controllers/UserController.ts
  src/v2/api/services/AuthService.ts
  src/v2/utils/exceptions/AbsenceOfCaptainTelegramException.ts
Labels: bug

#723 enhancement #711:Increase the number of characters in event name
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/CreateEventDTO.ts
  src/v2/api/dtos/UpdateEventDTO.ts
Labels: bug, enhancement

#715 enhancement #712: Added event url to Telegram endpoints
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/responses/EventsResponse.ts
  src/v2/api/responses/TelegramGeneralEventInfoResponse.ts
  src/v2/mappers/ScheduleMapper.ts
Labels: enhancement

#733 bugfix #730: added check for the existence of discipline teacher
  src/v2/security/group-guard/GroupByDisciplineTeacherGuard.ts
Labels: bug

#724 enhancement #713: made it possible to update telegramId
  src/v2/api/controllers/TelegramGroupController.ts
  src/v2/api/dtos/CreateTelegramGroupDTO.ts
  src/v2/api/dtos/UpdateTelegramGroupDTO.ts
Labels: enhancement

#738 enhancement #737: allow multiple permissions:
  src/v2/api/controllers/EntrantController.ts
  src/v2/api/controllers/ScheduleController.ts
  src/v2/security/Access.ts
  src/v2/security/permission-guard/Permission.ts
  src/v2/security/permission-guard/PermissionGuard.ts
  src/v2/security/permission-guard/Permissions.ts
Labels: enhancement

#742 enhancement #729: added logging of students verification by captain
  src/v2/api/services/UserService.ts
Labels: enhancement

#722 feature #710:Implemented endpoint for receiving groups with connected…
  src/v2/api/controllers/GroupController.ts
  src/v2/api/responses/GroupsWithTelegramGroupsResponse.ts
  src/v2/api/services/AuthService.ts
  src/v2/api/services/GroupService.ts
  src/v2/database/entities/DbGroup.ts
  src/v2/database/repositories/GroupRepository.ts
  src/v2/mappers/GroupMapper.ts
  src/v2/modules/GroupModule.ts
Labels: feature

#739 bugfix : fixed db events
  src/v2/api/services/ScheduleService.ts
Labels: bug

#741 migration #736: moved auth tokens to the database
  package.json
  prisma/migrations/20230917174654_add_auth_token/migration.sql
  prisma/schema.prisma
  src/v2/api/controllers/AuthController.ts
  src/v2/api/dtos/TelegramDTO.ts
  src/v2/api/dtos/UserDTO.ts
  src/v2/api/services/AuthService.ts
  src/v2/database/entities/DbStudent.ts
  src/v2/database/entities/DbUser.ts
  src/v2/database/repositories/StudentRepository.ts
  src/v2/database/repositories/UserRepository.ts
Labels: migration

#743 enhancement #740: add url validation:
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/dtos/CreateContactDTO.ts
  src/v2/api/dtos/UpdateContactDTO.ts
Labels: bug, enhancement

#755 bugfix: changed method to POST
  src/v2/api/controllers/PermissionController.ts
Labels: bug

#757 bugfix #756: fixed promises in auth
  src/v2/api/services/AuthService.ts
Labels: bug

#749 feature #745: implemented endpoint for exporting the list of students
  src/v2/api/controllers/GroupController.ts
  src/v2/api/datas/StudentWithContactsData.ts
  src/v2/api/responses/URLResponse.ts
  src/v2/api/services/GroupService.ispec.ts
  src/v2/api/services/GroupService.ts
  src/v2/modules/GroupModule.ts
  src/v2/security/PERMISSION.ts
  src/v2/utils/files/FileService.ts
Labels: feature

#748 enhancement #747: add sorting of students by last name
  src/v2/api/controllers/GroupController.ts
  src/v2/api/dtos/GroupStudentsQueryDTO.ts
  src/v2/api/services/GroupService.ts
Labels: enhancement
