Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-11, with the labels that each got.

#804 documentation #799: updated swagger doc for role endpoints
  src/v2/api/controllers/RoleController.ts
  src/v2/api/dtos/CreateGrantsDTO.ts
  src/v2/api/dtos/CreateRoleDTO.ts
  src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
  src/v2/api/dtos/UpdateRoleDTO.ts
  src/v2/api/responses/GrantResponse.ts
  src/v2/api/responses/RoleResponse.ts
Labels: documentation

#807 documentation #801: updated swagger doc for Poll endpoints:
  src/v2/api/controllers/PollController.ts
  src/v2/api/dtos/CreateQuestionDTO.ts
  src/v2/api/dtos/CreateQuestionRoleDTO.ts
  src/v2/api/dtos/CreateQuestionWithRolesDTO.ts
  src/v2/api/dtos/UpdateQuestionWithRolesDTO.ts
  src/v2/api/responses/PollDisciplineTeachersResponse.ts
  src/v2/api/responses/QuestionResponse.ts
  src/v2/api/responses/QuestionWithRolesResponse.ts
Labels: documentation

#820 bugfix #794: add ability to leave group
  src/v2/api/services/UserService.ts
  src/v2/utils/exceptions/DuplicateTelegramIdException.ts
Labels: bug

#808 documentation #766: update swagger doc for user 2
  src/v2/api/controllers/TeacherController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/dtos/CreateContactDTO.ts
  src/v2/api/dtos/GiveRoleDTO.ts
  src/v2/api/dtos/UpdateUserDTO.ts
  src/v2/api/responses/ContactResponse.ts
  src/v2/api/responses/ContactsResponse.ts
  src/v2/api/responses/UserResponse.ts
Labels: documentation

#827 migration #754: linked groups to their cathedra
  prisma/migrations/20231104142359_linked_groups_to_their_cathedra/migration.sql
  prisma/schema.prisma
  src/v2/api/controllers/RoleController.ts
  src/v2/api/services/ScheduleService.ispec.ts
Labels: migration

#834 migration #752: Added educational programs table
  prisma/migrations/20231107130331_add_educational_programs_table/migration.sql
  prisma/schema.prisma
  src/v2/api/services/ScheduleService.ispec.ts
Labels: migration

#836 documentation #768: updated swagger for auth endpoints
  src/v2/api/controllers/AuthController.ts
  src/v2/api/dtos/ForgotPasswordDTO.ts
  src/v2/api/dtos/IdentityQueryDTO.ts
  src/v2/api/dtos/ResetPasswordDTO.ts
  src/v2/api/dtos/VerificationEmailDTO.ts
  src/v2/api/responses/JWTTokensResponse.ts
  src/v2/api/responses/StudentResponse.ts
  src/v2/api/services/AuthService.ts
Labels: documentation

#835 feature #774: Created endpoint for deleting cathedras
  src/v2/api/controllers/CathedraController.ts
  src/v2/api/services/CathedraService.ts
  src/v2/database/repositories/CathedraRepository.ts
  src/v2/security/PERMISSION.ts
Labels: feature

#837 documentation #800: updated swagger doc for role endpoints:
  src/v2/api/controllers/RoleController.ts
  src/v2/api/dtos/CreateGrantsDTO.ts
  src/v2/api/responses/GrantResponse.ts
Labels: documentation

#819 documentation #818: updated swagger doc for user endpoints:
  src/v2/api/controllers/UserController.ts
  src/v2/api/dtos/CreateContactDTO.ts
  src/v2/api/dtos/UpdateContactDTO.ts
  src/v2/api/dtos/UpdateStudentDTO.ts
  src/v2/api/pipes/ContactByUserIdPipe.ts
  src/v2/api/responses/ContactResponse.ts
Labels: documentation

#845 bugfix #781: fixed typos in the password recovery letter
  src/v2/api/services/AuthService.ts
Labels: bug

#841 documentation #798: updated swagger doc for group endpoints
  src/v2/api/controllers/GroupController.ts
  src/v2/api/dtos/GroupStudentsQueryDTO.ts
  src/v2/api/dtos/QuerySemesterDTO.ts
  src/v2/api/responses/CaptainResponse.ts
  src/v2/api/responses/DisciplineResponse.ts
  src/v2/api/responses/DisciplineTeachersResponse.ts
  src/v2/api/responses/GroupStudentsResponse.ts
  src/v2/api/responses/StudentResponse.ts
  src/v2/api/responses/SubjectResponse.ts
  src/v2/api/responses/TeacherResponse.ts
Labels: documentation

#843 documentation #817: Updated Swagger documentation for Auth endpoints
  src/v2/api/controllers/AuthController.ts
  src/v2/api/responses/TokenResponse.ts
Labels: documentation

#839 Feature/better discipline teachers
  src/v2/api/controllers/PollController.ts
  src/v2/api/dtos/QueryAllDisciplineTeacherForPollDTO.ts
  src/v2/api/dtos/QueryAllTeacherDTO.ts
  src/v2/api/services/PollService.ispec.ts
  src/v2/api/services/PollService.ts
  src/v2/api/services/TeacherService.ispec.ts
  src/v2/api/services/TeacherService.ts
  src/v2/database/DatabaseUtils.ts
  src/v2/mappers/DisciplineMapper.ts
  src/v2/mappers/DisciplineTeacherMapper.ts
  src/v2/utils/ArrayUtil.ts
Labels: enhancement

#814 feature #772: Created endpoint for receiving all cathedras
  src/v2/api/controllers/CathedraController.ts
  src/v2/api/dtos/QueryAllCathedrasDTO.ts
  src/v2/api/responses/CathedraWithNumberOfTeachersResponse.ts
  src/v2/api/responses/PaginatedCathedrasWithTeachersResponse.ts
  src/v2/api/services/CathedraService.ts
  src/v2/database/repositories/CathedraRepository.ts
  src/v2/mappers/CathedraMapper.ts
Labels: feature

#828 enhancement #826: upgraded prisma version to 4.16
  package.json
  src/v2/api/services/GroupService.ts
  src/v2/api/services/PollService.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/api/services/UserService.ts
  src/v2/database/repositories/DisciplineRepository.ts
  src/v2/database/repositories/EventRepository.ts
  src/v2/database/repositories/GroupRepository.ts
  src/v2/database/repositories/StudentRepository.ts
  yarn.lock
Labels: enhancement

#853 enhancement #829: improved ApiEndpoint for working with TelegramGuard
  src/v2/api/controllers/AuthController.ts
  src/v2/api/controllers/GroupController.ts
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/controllers/TelegramGroupController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/utils/documentation/decorators.ts
Labels: enhancement

#866 enhancement: added delay before migration
  .github/workflows/build.yml
  .github/workflows/deployment.yml
Labels: enhancement

#847 documentation #816: updated swagger for permission and telegram group…
  src/v2/api/controllers/PermissionController.ts
  src/v2/api/controllers/TelegramGroupController.ts
  src/v2/api/dtos/CheckPermissionsDTO.ts
  src/v2/api/dtos/CreateTelegramGroupDTO.ts
  src/v2/api/dtos/UpdateTelegramGroupDTO.ts
  src/v2/api/responses/CheckPermissionsResponse.ts
  src/v2/api/responses/TelegramGroupByTelegramIdResponse.ts
  src/v2/api/responses/TelegramGroupResponse.ts
Labels: documentation

#840 feature #734: Implemented CRUD endpoints for grants
  src/v2/api/controllers/GrantController.ts
  src/v2/api/controllers/RoleController.ts
  src/v2/api/dtos/CreateGrantsDTO.ts
  src/v2/api/dtos/CreateRoleDTO.ts
  src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
  src/v2/api/dtos/QueryAllGrantsDTO.ts
  src/v2/api/dtos/QueryAllRolesDTO.ts
  src/v2/api/dtos/SortQAGParam.ts
  src/v2/api/dtos/SortQARParam.ts
  src/v2/api/dtos/UpdateGrantDTO.ts
  src/v2/api/pipes/GrantByIdPipe.ts
  src/v2/api/pipes/RoleByIdPipe.ts
  src/v2/api/responses/GrantResponse.ts
  src/v2/api/responses/GrantsResponse.ts
  src/v2/api/responses/RoleResponse.ts
  src/v2/api/responses/RolesResponse.ts
  src/v2/api/services/GrantService.ts
  src/v2/api/services/RoleService.spec.ts
  src/v2/api/services/RoleService.ts
  src/v2/database/repositories/GrantRepository.ts
  src/v2/database/repositories/RoleRepository.ts
  src/v2/mappers/GrantMapper.ts
  src/v2/mappers/RoleMapper.ts
  src/v2/security/PERMISSION.ts
Labels: feature

#838 feature #833: created an endpoint for bot to create events
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/dtos/CreateEventDTO.ts
  src/v2/api/responses/MainEventInfoResponse.ts
  src/v2/api/responses/TelegramGeneralEventInfoResponse.ts
  src/v2/mappers/ScheduleMapper.ts
Labels: feature

#854 feature #848: Created an endpoint for deleting disciplines
  src/v2/api/controllers/DisciplineController.ts
  src/v2/api/services/DisciplineService.ts
  src/v2/database/repositories/DisciplineRepository.ts
  src/v2/mappers/DisciplineMapper.ts
  src/v2/security/PERMISSION.ts
Labels: feature

#873 enhancement: week query for getGroupEventsByDay
  src/v2/api/controllers/ScheduleController.ts
  src/v2/api/controllers/UserController.ts
  src/v2/api/dtos/UpdateGroupDTO.ts
  src/v2/api/services/ScheduleService.ts
  src/v2/utils/date/DateService.ispec.ts
Labels: enhancement
