Repository fictadvisor/fictadvisor-api, pull requests merged in 2023-04, with the labels that each got.

#298 bug/Allow_deletion_of_middleName_of_user
  src/v2/api/auth/dto/StudentDTO.ts
  src/v2/api/user/dto/UpdateStudentDTO.ts
  yarn.lock
Labels: bug

#291 feature/Add_endpoint_for_ADU_teachers_on_the_subject
  src/v2/api/discipline/DisciplineRepository.ts
  src/v2/api/discipline/DisciplineTypeRepository.ts
  src/v2/api/discipline/DisciplineTypeService.ts
  src/v2/api/discipline/pipe/DisciplineByIdPipe.ts
  src/v2/api/schedule/ScheduleService.ts
  src/v2/api/subject/SubjectRepository.ts
  src/v2/api/teacher/DisciplineTeacherController.ts
  src/v2/api/teacher/DisciplineTeacherRepository.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/api/teacher/TeacherRepository.ts
  src/v2/api/teacher/data/CreateDisciplineTeacherDTO.ts
  src/v2/api/teacher/data/CreateDisciplineTeacherData.ts
  src/v2/api/teacher/data/CreateDisciplineTeacherWithRolesData.ts
  src/v2/api/teacher/dto/TeacherRoleAdapter.ts
  src/v2/api/teacher/dto/UpdateDisciplineTeacherDTO.ts
  src/v2/api/teacher/pipe/TeacherByIdPipe.ts
  src/v2/utils/exceptions/NullObjectException.ts
Labels: feature

#303 #267migration/added_a_column_to_determine_the_order_of_questions
  prisma/migrations/20230411175521_question_add_column_to_define_order/migration.sql
  prisma/schema.prisma
  src/v2/api/teacher/DisciplineTeacherRepository.ts
Labels: migration

#299 Refactoring/refactor user repository
  src/v2/api/auth/AuthService.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/user/ContactByUserIdPipe.ts
  src/v2/api/user/UserByIdPipe.ts
  src/v2/api/user/UserController.ts
  src/v2/api/user/UserMapper.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/UserRepository.ts
  src/v2/api/user/UserService.ts
  src/v2/api/user/data/CreateUserData.ts
  src/v2/api/user/data/UpdateUserData.ts
  src/v2/api/user/role/RoleRepository.ts
  src/v2/api/user/role/RoleService.ts
Labels: refactoring

#309 refactoring/subject-methods
  src/v2/api/subject/DbSubject.ts
  src/v2/api/subject/SubjectByIdPipe.ts
  src/v2/api/subject/SubjectController.ts
  src/v2/api/subject/SubjectMapper.ts
  src/v2/api/subject/SubjectModule.ts
  src/v2/api/subject/SubjectRepository.ts
  src/v2/api/subject/SubjectService.ts
  src/v2/api/subject/data/CreateSubjectData.ts
  src/v2/api/subject/data/UpdateSubjectData.ts
  src/v2/api/teacher/TeacherRepository.ts
Labels: refactoring

#308 enhancement #267: sort questions by order
  src/v2/api/poll/QuestionAnswerRepository.ts
  src/v2/api/poll/QuestionRepository.ts
  src/v2/api/poll/data/CreateQuestionWithRolesData.ts
  src/v2/api/poll/dto/CreateQuestionDTO.ts
  src/v2/api/poll/dto/UpdateQuestionDTO.ts
  src/v2/api/teacher/DisciplineTeacherRepository.ts
Labels: enhancement

#315 refactoring #304: refactored role repository
  src/v2/api/auth/AuthService.ts
  src/v2/api/group/GroupService.ts
  src/v2/api/user/UserModule.ts
  src/v2/api/user/data/CreateGrantData.ts
  src/v2/api/user/data/CreateGrantInRoleData.ts
  src/v2/api/user/data/CreateRoleData.ts
  src/v2/api/user/dto/CreateGrantsDTO.ts
  src/v2/api/user/grant/GrantController.ts
  src/v2/api/user/grant/GrantMapper.ts
  src/v2/api/user/grant/GrantRepository.ts
  src/v2/api/user/grant/GrantService.ts
  src/v2/api/user/role/RoleController.ts
  src/v2/api/user/role/RoleMapper.ts
  src/v2/api/user/role/RoleRepository.ts
  src/v2/api/user/role/RoleService.ts
Labels: refactoring

#319 refactoring #288: refactored discipline teacher service
  src/v2/api/teacher/DisciplineTeacherController.ts
  src/v2/api/teacher/DisciplineTeacherService.ts
  src/v2/utils/date/DateService.ts
Labels: refactoring
